// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.Models;

public partial class Cart
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public virtual ICollection<CartAccommodationDetail> CartAccommodationDetails { get; set; } = new List<CartAccommodationDetail>();

    public virtual ICollection<CartActivitiesDetail> CartActivitiesDetails { get; set; } = new List<CartActivitiesDetail>();

    public virtual ICollection<CartExtraServicesDetail> CartExtraServicesDetails { get; set; } = new List<CartExtraServicesDetail>();

    public virtual Member Member { get; set; }
}