// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.Models;

public partial class CommentsAccommodation
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int AccommodationId { get; set; }

    public int Score { get; set; }

    public string Title { get; set; }

    public string Pros { get; set; }

    public string Cons { get; set; }

    public DateTime CreateDate { get; set; }

    public int CommentStatusId { get; set; }

    public string Reply { get; set; }

    public DateTime? ReplyAt { get; set; }

    public virtual Accommodation Accommodation { get; set; }

    public virtual ICollection<CommentAccommodationLike> CommentAccommodationLikes { get; set; } = new List<CommentAccommodationLike>();

    public virtual CommentStatus CommentStatus { get; set; }

    public virtual ICollection<CommentsAccommodationImage> CommentsAccommodationImages { get; set; } = new List<CommentsAccommodationImage>();

    public virtual Member Member { get; set; }
}