// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.Models;

public partial class ExtraService
{
    public int Id { get; set; }

    public int RegionId { get; set; }

    public int AttractionId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool Status { get; set; }

    public string Image { get; set; }

    public virtual Attraction Attraction { get; set; }

    public virtual ICollection<ExtraServiceImage> ExtraServiceImages { get; set; } = new List<ExtraServiceImage>();

    public virtual ICollection<ExtraServiceProduct> ExtraServiceProducts { get; set; } = new List<ExtraServiceProduct>();

    public virtual ICollection<OrderExtraServicesDetail> OrderExtraServicesDetails { get; set; } = new List<OrderExtraServicesDetail>();

    public virtual Region Region { get; set; }

    public virtual ICollection<PackageTour> PackageTours { get; set; } = new List<PackageTour>();
}