// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.Models;

public partial class ExtraServiceProduct
{
    public int Id { get; set; }

    public int ExtraServiceId { get; set; }

    public DateTime Date { get; set; }

    public int Price { get; set; }

    public int Quantity { get; set; }

    public virtual ICollection<CartExtraServicesDetail> CartExtraServicesDetails { get; set; } = new List<CartExtraServicesDetail>();

    public virtual ExtraService ExtraService { get; set; }

    public virtual ICollection<OrderExtraServicesDetail> OrderExtraServicesDetails { get; set; } = new List<OrderExtraServicesDetail>();

    public virtual ICollection<TravelPlan> TravelPlans { get; set; } = new List<TravelPlan>();
}