// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.Models;

public partial class PackageTour
{
    public int Id { get; set; }

    public string Description { get; set; }

    public bool Status { get; set; }

    public int PackageCouponId { get; set; }

    public virtual PackageCoupon PackageCoupon { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    public virtual ICollection<Attraction> Attractions { get; set; } = new List<Attraction>();

    public virtual ICollection<ExtraService> ExtraServices { get; set; } = new List<ExtraService>();
}