// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.Models;

public partial class RoomProduct
{
    public int Id { get; set; }

    public int RoomId { get; set; }

    public DateTime Date { get; set; }

    public decimal NewPrice { get; set; }

    public int Quantity { get; set; }

    public virtual ICollection<CartAccommodationDetail> CartAccommodationDetails { get; set; } = new List<CartAccommodationDetail>();

    public virtual ICollection<OrderAccommodationDetail> OrderAccommodationDetails { get; set; } = new List<OrderAccommodationDetail>();

    public virtual Room Room { get; set; }
}