// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterFrontend.Models;

public partial class ServiceInfoCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<AccommodationServiceInfo> AccommodationServiceInfos { get; set; } = new List<AccommodationServiceInfo>();

    public virtual ICollection<RoomServiceInfo> RoomServiceInfos { get; set; } = new List<RoomServiceInfo>();
}