// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterService.Models;

public partial class Attraction
{
    public int Id { get; set; }

    public int AttractionCategoryId { get; set; }

    public string Name { get; set; }

    public int RegionId { get; set; }

    public int TownId { get; set; }

    public string Address { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public string Website { get; set; }

    public double? PositionX { get; set; }

    public double? PositionY { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    public virtual AttractionCategory AttractionCategory { get; set; }

    public virtual ICollection<AttractionClick> AttractionClicks { get; set; } = new List<AttractionClick>();

    public virtual ICollection<AttractionImage> AttractionImages { get; set; } = new List<AttractionImage>();

    public virtual ICollection<CommentsAttraction> CommentsAttractions { get; set; } = new List<CommentsAttraction>();

    public virtual ICollection<ExtraService> ExtraServices { get; set; } = new List<ExtraService>();

    public virtual ICollection<FavoriteAttraction> FavoriteAttractions { get; set; } = new List<FavoriteAttraction>();

    public virtual Region Region { get; set; }

    public virtual Town Town { get; set; }

    public virtual ICollection<PackageTour> PackageTours { get; set; } = new List<PackageTour>();

    public virtual ICollection<AttractionTag> Tags { get; set; } = new List<AttractionTag>();

    public virtual ICollection<TravelPlan> TravelPlans { get; set; } = new List<TravelPlan>();
}