// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterService.Models;

public partial class Member
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Account { get; set; }

    public string EncryptedPassword { get; set; }

    public string Email { get; set; }

    public string CellPhoneNumber { get; set; }

    public string Address { get; set; }

    public bool? Gender { get; set; }

    public DateTime? Birthday { get; set; }

    public DateTime CreateDate { get; set; }

    public string Image { get; set; }

    public bool IsConfirmed { get; set; }

    public string ConfirmCode { get; set; }

    public string GoogleAccessCode { get; set; }

    public string FaceBookAccessCode { get; set; }

    public string LineAccessCode { get; set; }

    public bool IsSuspended { get; set; }

    public DateTime? LoginTime { get; set; }

    public bool IsSuscribe { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<CommentAccommodationLike> CommentAccommodationLikes { get; set; } = new List<CommentAccommodationLike>();

    public virtual ICollection<CommentsAccommodation> CommentsAccommodations { get; set; } = new List<CommentsAccommodation>();

    public virtual ICollection<CommentsAttraction> CommentsAttractions { get; set; } = new List<CommentsAttraction>();

    public virtual ICollection<FavoriteAttraction> FavoriteAttractions { get; set; } = new List<FavoriteAttraction>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual ICollection<SystemMessage> SystemMessages { get; set; } = new List<SystemMessage>();

    public virtual ICollection<TravelPlan> TravelPlans { get; set; } = new List<TravelPlan>();
}