// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterService.Models;

public partial class PackageCoupon
{
    public int Id { get; set; }

    public double Discount { get; set; }

    public virtual ICollection<PackageTour> PackageTours { get; set; } = new List<PackageTour>();
}