// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterService.Models;

public partial class Permission
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Administrator> Administrators { get; set; } = new List<Administrator>();
}