// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RouteMasterService.Models;

public partial class Town
{
    public int Id { get; set; }

    public int RegionId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Accommodation> Accommodations { get; set; } = new List<Accommodation>();

    public virtual ICollection<Attraction> Attractions { get; set; } = new List<Attraction>();

    public virtual Region Region { get; set; }
}